name           = "App-Greple-stripe"
badges         = [ "github-actions/test.yml" ]
module_maker   = "ModuleBuildTiny"
static_install = "auto"

[release]
branch = "main"
hooks = [
    "make -C docs",
]

[FileGatherer]
exclude_match = [ '^images/', '^docs/.*\.json' ]

[no_index]
directory = [ 't', 'xt', 'docs' ]

